# Generated by Django 3.2.13 on 2022-06-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prix', models.FloatField(default=0)),
                ('quantite', models.IntegerField(default=0)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_creaction', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
